:: TODO

@echo off

setlocal enabledelayedexpansion

set Err=

set ArgCount=0
for %%I in (%*) do (
    set /A ArgCount+=1
    set "ArgVec[!ArgCount!]=%%~I"
)

rem Default fallback if MSVC does not automatically set platform
if "%Platform%"=="" set Platform=x64

rem Default build configuration
set Config=Debug

rem Set variable to hold various MSBuild options
set "Opts= "

rem Set project root directory
set Root=%~dp0..
for %%I in ("%Root%") do set "Root=%%~fI"

rem Configure development environment
if not defined DevEnvDir (
    call "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform%
)

rem Process command-line arguments arguments
for /L %%I in (1,1,%ArgCount%) do (
    
    set Arg=!ArgVec[%%I]!

    if !Arg! EQU clean goto :Clean

    if !Arg! EQU release (
        set Config=Release
    )
    if !Arg! EQU rebuild (
        call set "Opts=%%Opts%% -t:Rebuild"
    )
    
)
if %ErrorLevel% neq 0 goto :Error

rem End of entry point procedure
goto :Main


::-----------------------------------------------------------------------------
:: Main
::-----------------------------------------------------------------------------
rem Main procedure that configurues the script environment and LSP compile flags
:Main

rem Define `compile_flags.txt` file for the LLVM Clang LSP
set CompileFlags=compile_flags.txt

rem Clear `compile_flags.txt` file
echo | set /p Clear="" > %CompileFlags%

rem Set the `include` directory
set IncDir=%Root%\Iconoclast\include

rem Clear variables to store include filenames
set Incs=

call :IncludeDirs %IncDir%
if %ErrorLevel% neq 0 goto :Error

rem End of :Main subroutine call
goto :Build


::-----------------------------------------------------------------------------
:: Build
::-----------------------------------------------------------------------------
rem Calls MSBuild to build the solution
:Build

call MSBuild Iconoclast.sln -p:Configuration=%Config% %Opts:~1%

if %ErrorLevel% neq 0 goto :Error

rem End of :Build subroutine call
goto :EOF


::===========================================================================
:: Helper Routines
::===========================================================================


::-----------------------------------------------------------------------------
:: Clean
::-----------------------------------------------------------------------------
rem Deletes all intermediary and binary files generated by the previous build(s)
:Clean

call MSBuild Iconoclast.sln -t:clean

rem End of :Clean subroutine call
goto :EOF


::-----------------------------------------------------------------------------
:: Relative Path
::-----------------------------------------------------------------------------
rem Gets the relative path from the given absolute path
:RelativePath

set "AbsPath=%1%"
set "RelPath=!AbsPath:%Root%=!"

rem End of :RelativePath subroutine call
goto :EOF


::-----------------------------------------------------------------------------
:: Include Directories
::-----------------------------------------------------------------------------
rem Reference the absolute and relative directory path of each `*.h` header file
:IncludeDirs

for /r %1 %%F in (*.h) do (

    call :RelativePath %%~dpF

    rem Prevent duplicate include directories
    if !Prev! neq !RelPath! (

        call set "Incs=%%Incs%% -I%Root%!RelPath:~0,-1!"
        call :AddCompileFlag !RelPath!

        set "Prev=!RelPath!"
    )
)

rem End of :IncludeFiles subroutine call
goto :EOF


::-----------------------------------------------------------------------------
:: Compile Flags
::-----------------------------------------------------------------------------
rem Adds a compile flag to `compile_flags.txt` for the Clang LSP.
:AddCompileFlag

echo %1

set Flag=%1

rem Invert slashes for include paths to be compatible with the LSP
set FilePath=!Flag:\=/!
echo -I>> %Root%\%CompileFlags%
echo .!FilePath!>> %Root%\%CompileFlags%

rem End of :AddCompileFlag subroutine call
goto :EOF


::-----------------------------------------------------------------------------
:: Error
::-----------------------------------------------------------------------------
rem Error function to call when a build error is encountered
:Error

set Err=%ErrorLevel%
echo. 
echo Build failed
echo Error code: %ErrorLevel%

rem Exit program with error code
exit /b %ErrorLevel%
